name: Publish Python Package

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
    tags:
      - "v*"  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can change the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Run your tests, make sure you have `pytest` in requirements.txt if you use it

    - name: Build and upload package to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD